### ISSUE TITLE
Unable to Reconfigure Credentials

### ISSUE THREAD

**Issue by nqeldridge** [dahlb/ha_hatch#104]
It appears there is no way to update your username/password after the initial configuration.  I changed the password of my Hatch account and now the device is showing a login error, but I cannot find where to update the password.

**Comment by dahlb** [comment]
the default response seems to be to delete and re-add the integration, example https://community.home-assistant.io/t/ring-integration-change-username-password/388674

however if you provide the logs by adding
```
logger:
  default: warning
  logs:
    custom_components.ha_hatch: debug
    hatch_rest_api: debug
```

I should be able to see the error the api provides and trigger a re-auth flow as outlined at https://developers.home-assistant.io/docs/integration_setup_failures/#handling-expired-credentials
